### ISSUE TITLE
Cascade Coding

### ISSUE THREAD

**Issue by iute** [xdsopl/reedsolomon#1]
Have you studied cascade coding?

**Comment by xdsopl** [comment]
Never have heard of it before. Can you elaborate or provide a paper about it?

**Comment by iute** [comment]
> Sorry, I may have translated it wrong, it may be called  cascade code, which is a combination of two error correction codes. As an example, here's a paper from a long time ago, called"[Performance of RS-BCH Concatenated Codes and BCH Single-Stage Codes on an Interference Satellite Channel](http://ieeexplore.ieee.org/document/1096813/)"

**Comment by iute** [comment]
I am studying FEC, if I don't know any questions can I ask you?

**Comment by xdsopl** [comment]
Ahh, yes, cascade != concatenate. Concatenating codes is a well know technique to combine an practically soft decodable (usually a convolutional or LDPC) inner code with an hard decodable, (usually BCH or RS) algebraic outer code to improve the error floor or burst error behavior of the inner code:
https://en.wikipedia.org/wiki/Concatenated_error_correction_code

**Comment by iute** [comment]
Thanks for the explanation, but I didn't find the code information of the concatenating codes on github, or maybe I searched for the wrong keywords, what should I do?

**Comment by xdsopl** [comment]
Learning how to search and where to look is part of your studies. You have to do that yourself. Good luck!
